name: whatsapp_sender
description: WhatsApp Sender is an unofficial API to send bulk messages in Whatsapp
version: 0.0.1
homepage: https://github.com/patricknicolosi/whatsapp_sender

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  puppeteer: ^2.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

