name: whatsapp_sender_flutter
description: WhatsApp Sender Flutter is an unofficial API for Flutter to send bulk messages in Whatsapp
version: 0.0.9
homepage: https://github.com/patricknicolosi/whatsapp_sender_flutter

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  puppeteer: ^2.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

